fragment VehicleDetails on Vehicle {
    id
    title
    description
    icons {
        medium
    }
    level
    type {
        name
        title
        icons {
            default
        }
    }
    nation {
        name
        title
        color
        icons {
            tiny
        }
    }
}